remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom
- top


title: "Pixel Create"
description: "Creating art one pixel at a time!"
version: "1.0.0"
author:
  name: "Mark Vega"
  email: "mvega37@student.cnm.edu"

# Do not change the following line.
  copyright: true

kramdown:
  toc_levels: 2..3